# Generated by Django 4.2.4 on 2023-08-11 16:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('passwords', models.TextField()),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
