# Generated by Django 4.2.4 on 2023-08-11 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_v22', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('post_date', models.DateTimeField(default=datetime.datetime(2023, 8, 11, 20, 23, 49, 469346))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facebook_v22.user')),
            ],
        ),
    ]
